FROM node:18-bullseye
RUN apt-get update
ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY socket/package.json /home/node/socket/
WORKDIR /home/node/socket/
RUN npm install
RUN chmod a+rwx /home/node/socket/node_modules