FROM node:18-bullseye
RUN apt-get update && apt-get install -q -y sudo vim
ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY client/package.json /home/node/client/
WORKDIR /home/node/client/
RUN npm install
RUN chmod a+rwx /home/node/client/node_modules